export {
  MAX_TITLE_LENGTH,
  MAX_SUBTITLE_LENGTH,
  MAX_SEO_TITLE_LENGTH,
  MAX_META_DESCRIPTION_LENGTH,
  MAX_AUTHOR_LENGTH,
  MIN_TITLE_LENGTH,
  MIN_SUBTITLE_LENGTH,
  MIN_SEO_TITLE_LENGTH,
  MIN_META_DESCRIPTION_LENGTH,
  MIN_CONTENT_TEXT_LENGTH,
} from './content';
