# .github/workflows/ci.yml  (or your existing file)
name: test-and-build

on: [push, pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ① Install PNPM (and enable Corepack)
      - name: Set up PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8 # lock to a specific major if you wish
          run_install: false # we’ll call pnpm install manually

      - name: Enable Corepack (makes pnpm available in $PATH)
        run: corepack enable

      # ② Install dependencies
      - name: Install deps
        run: pnpm install --frozen-lockfile

      # ③ Lint, test, build
      - name: Lint
        run: pnpm run lint

      - name: Unit tests
        run: pnpm run test

      - name: Build
        run: pnpm run build

      # ④ (Optional) Upload Playwright report
      - name: Upload Playwright HTML report
        if: always() # still upload on failures
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
